server:
  port: 8080
  servlet.context-path: /config-server

spring:
  application:
    name: config-server
  profiles:
    active: dev

global:
  extension: .yml
  base-path: /test/
  commitHistorySize: 10
